### ISSUE TITLE
List Questions

### ISSUE THREAD

**Issue by MeenaFoerderer** [MeenaFoerderer/Ask-a-dev#1]
## Value proposition

As a user
I want to see a list of questions,
so that I can browse questions that were already asked by other users

## Description

[wireframe]

## Acceptance criteria

- existing questions are displayed in a list on the landing page
- questions are displayed one below the other

## Tasks

 - [ ] open feature branch
 - [ ] fetch questions from API with SWR

💡 `install the swr package`

💡 `the list of questions endpoint is on GET /api/questions`

💡 `feel free to use the hostname https://www.ask-a.dev to build the path yourself or use the preconfigured hostname and fetcher in helpers/api.js`

- [ ] create unordered list with one list item for each question

💡 `the api endpoint returns the list of questions without the answers key, unlike the fake data.`

## Complexity Estimation

S
